### ISSUE TITLE
参加申請

### ISSUE THREAD

**Issue by NekobaTechnology** [MetLaboratory/member#7]
# Issueテンプレート

## Twitterのリンク
[@futanyaha](https://twitter.com/futanyaha)

## Metさんとの関係
[Metさんを監視している人](https://twitter.com/search?q=from%3Afutanyaha%20Met&src=typed_query&f=live)

## 希望役職
ねこ

## コメント(README.mdのメンバー紹介で使用)
meow

## 志望動機
Metさんの周りに集まる人たちでおもしろいことが起きそうだから。
広く浅くいろいろできます。

**Comment by Akirtn** [comment]
すでに参加しているような 🤔
